[workspace]
resolver = "2"
members = [
  "crates/assets",
  "crates/logging",
]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
# External crates
gpui = "=0.2.2"
rust-embed = "=8.9.0"
thiserror = "=2.0.17"
tracing = "=0.1.41"
tracing-subscriber = "=0.3.20"

# Internal crates
assets = { path = "crates/assets" }
logging = { path = "crates/logging" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
indexing_slicing = "deny"
