[package]
name = "components"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
# External crates
iced.workspace = true
tracing.workspace = true

# Internal crates
assets.workspace = true
types.workspace = true


[lints]
workspace = true
