[package]
name = "components"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
# External crates
gpui.workspace = true
gpui-component.workspace = true

# Internal crates


[lints]
workspace = true
