[package]
name = "validate"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/validate.rs"

[dependencies]
# External crates
gpui.workspace = true
gpui-component.workspace = true
thiserror.workspace = true

# Internal crates

[lints]
workspace = true
