[package]
name = "logging"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lib]
path = "src/logging.rs"

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
