[package]
name = "types"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
# External crates
gpui-component.workspace = true
gpui.workspace = true
strum.workspace = true
strum_macros.workspace = true
uuid.workspace = true

[lints]
workspace = true
