[package]
name = "initiative"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
# External crates
iced.workspace = true
tracing.workspace = true

# Internal crates
app.workspace = true
logging.workspace = true

[lints]
workspace = true
